import type { SidebarsConfig } from '@docusaurus/plugin-content-docs'

const sidebars: SidebarsConfig = {
    lections: [{ type: 'autogenerated', dirName: 'lections' }],
    terms: [{ type: 'autogenerated', dirName: 'defs' }]
}

export default sidebars
